"""Tests for apcore_toolkit.output.yaml_writer — YAMLWriter."""

from __future__ import annotations

from pathlib import Path

import yaml

from apcore_toolkit.output.yaml_writer import YAMLWriter
from apcore_toolkit.types import ScannedModule


class TestYAMLWriterDryRun:
    def setup_method(self) -> None:
        self.writer = YAMLWriter()

    def test_empty_modules(self) -> None:
        result = self.writer.write([], "/tmp/out", dry_run=True)
        assert result == []

    def test_single_module(self, sample_module: ScannedModule) -> None:
        result = self.writer.write([sample_module], "/tmp/out", dry_run=True)
        assert len(result) == 1
        binding = result[0]
        assert "bindings" in binding
        assert len(binding["bindings"]) == 1
        assert binding["bindings"][0]["module_id"] == "users.get_user"

    def test_binding_contains_all_fields(self, annotated_module: ScannedModule) -> None:
        result = self.writer.write([annotated_module], "/tmp/out", dry_run=True)
        binding = result[0]["bindings"][0]
        assert binding["module_id"] == "tasks.create_task"
        assert binding["target"] == "myapp.views:create_task"
        assert binding["description"] == "Create a new task"
        assert binding["documentation"] == "Create a new task with the given title."
        assert binding["tags"] == ["tasks"]
        assert binding["version"] == "2.0.0"
        assert binding["annotations"]["destructive"] is True
        assert binding["metadata"]["http_method"] == "POST"

    def test_multiple_modules(self, sample_module: ScannedModule, annotated_module: ScannedModule) -> None:
        result = self.writer.write([sample_module, annotated_module], "/tmp/out", dry_run=True)
        assert len(result) == 2


class TestYAMLWriterFileOutput:
    def setup_method(self) -> None:
        self.writer = YAMLWriter()

    def test_writes_files(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        self.writer.write([sample_module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1
        content = files[0].read_text()
        assert "Auto-generated by apcore-toolkit scanner" in content
        parsed = yaml.safe_load(content)
        assert parsed["bindings"][0]["module_id"] == "users.get_user"

    def test_creates_output_dir(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        out_dir = tmp_path / "nested" / "output"
        self.writer.write([sample_module], str(out_dir))
        assert out_dir.exists()
        assert len(list(out_dir.glob("*.binding.yaml"))) == 1

    def test_filename_sanitization(self, tmp_path: Path) -> None:
        module = ScannedModule(
            module_id="weird/id..test",
            description="test",
            input_schema={},
            output_schema={},
            tags=[],
            target="m:f",
        )
        self.writer.write([module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1
        # Slashes replaced, double-dots collapsed
        filename = files[0].name
        assert "/" not in filename
        assert ".." not in filename

    def test_overwrite_existing(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        self.writer.write([sample_module], str(tmp_path))
        self.writer.write([sample_module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1

    def test_none_annotations_in_output(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        result = self.writer.write([sample_module], str(tmp_path), dry_run=True)
        assert result[0]["bindings"][0]["annotations"] is None
